---
title: "Data processing for amCharts sunburst"
author: "Hollie Rawlings"
date: "10/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rjson)
library(jsonlite)
```

## Data call 

```{r}
continent_list <-read.csv("data/Continent_list.csv")
soybean_farming<- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-06/soybean_use.csv')
```

## Data proprocessing 
Same processing as in the deforestation code 
```{r}
continent_list <-read.csv("data/Continent_list.csv")

soybean_farming <- soybean_farming %>% 
  inner_join(continent_list,by=c("code"="Three_Letter_Country_Code"))%>%
  select(entity,code,year,human_food,animal_feed,processed,`ï..Continent_Name`)%>%
  rename(Continent=`ï..Continent_Name`)

continent_allocation <- soybean_farming %>% select(entity,Continent)%>%
  unique()
## These countries are 	Armenia,Azerbaijan,Cyprus,Georgia,Kazakhstan,Russia,Turkey 
## There are not many, so I can use a case when to recode them. 
## I'm no geography expert so I may not be right, If this were go go in a paper I would have to include a footnote about these allocations

soybean_farming <- soybean_farming %>% 
  mutate(Continent = case_when(
    entity == "Armenia" ~ "Europe",
    entity == "Azerbaijan" ~ "Asia", 
    entity == "Cyprus" ~ "Europe", 
    entity == "Georgia" ~ "Asia", 
    entity == "Kazakhstan" ~ "Asia", 
    entity == "Russia" ~ "Europe", 
    entity == "Turkey" ~ "Europe", 
    TRUE ~ Continent
  ))%>%
  unique() %>%
  filter(year ==2013)%>%
  select(-code)%>%
  rename(`human food` = human_food, `animal feed` = animal_feed)%>%
  pivot_longer(cols =c(`human food`,`animal feed`,processed))%>%
  filter(value != 0)%>%
  select(Continent,entity,name,value)
```

## mapping to JSON output object 

```{r}
## split the list by continent
Data_list <- split(soybean_farming, soybean_farming$Continent)

Countries <-data.frame(cont=Data_list$Africa$Continent, country=Data_list$Africa$entity)
Values <- data.frame(country=Data_list$Africa$entity, name=Data_list$Africa$name, value=Data_list$Africa$value)

library(hashmap)
H <- hashmap(Data_list$Africa$name, Data_list$Africa$value)

output <- jsonlite::toJSON(Africa,pretty=TRUE,auto_unbox = FALSE)
cat(output)
```
